New content for ReactionDiffusionSolverFE & Boundary Conditions pages; removed orphaned section pages
CompuCell3D/CompuCell3DReferenceManual pull request #33
Opened 2024-10-15 00:36 UTC by fyffep

Changes made:
1. Overhauled ReactionDiffusionSolverFE 
2. Added 2 Boundary Conditions pages
3. Removed orphaned section pages. These contained duplicate content of similarly-named pages (e.g. section_tutorials.rst and tutorials_section.rst)
4. Added many more hyperlinks to clarify technical jargon.

2024-10-15 00:42 UTC, fyffep commented on docs/images/movies/constant_derivative_diffusion.gif
GIFs are very useful, but I add 636 KB with just these 2 files. Should I work to reduce the image quality, or is this not much of a concern?

2024-10-15 00:42 UTC, fyffep commented on docs/reaction_diffusion_solver.rst
> +    * We recommend using either InitialConcentrationExpression or ConcentrationFileName but not both.
I could not confirm that `InitialConcentrationExpression` is a part of ReactionDiffusionSolverFE. It seems to be present in all of the other PDE solvers, however.

2024-10-15 00:42 UTC, fyffep commented on docs/boundary_conditions_cells.rst
> +##############################
This is somewhat duplicate content from potts.rst, but I think it's valuable to have smaller quick reference pages like this as well.

2025-07-05 17:42 UTC, maciekswat commented on docs/boundary_conditions_cells.rst
> +##############################
Agree

2025-07-05 17:43 UTC, maciekswat commented on docs/boundary_conditions_cells.rst
> +            <!-- Boundary_z>Periodic</Boundary_z --> <!--Use this for 3D-->
<!--Use this for 3D only, never for 2D simulations-->

2025-07-05 17:47 UTC, maciekswat commented on docs/boundary_conditions_diffusion.rst
> +ConstantDerivative uses a von Neumann Equation to control the curvature of a diffusing substrate defined by a ConstantValue boundary condition.
I woudl remove this sentence

2025-07-05 17:47 UTC, maciekswat commented on docs/boundary_conditions_diffusion.rst
> +
Let's add this sentence:
The primary use of  ``ConstantDerivative boundary conditions is to implement zero flux across the simulation boundary. This ensures that the chemical does not flow out of the simulation domain

2025-07-05 17:50 UTC, maciekswat commented on docs/boundary_conditions_diffusion.rst
> +This mode should not be used on its own; rather, it is meant to be combined with ConstantValue diffusion to create nonlinear patterns of substrates.
And I would replace this sentence with the following one:
Alternatively, one could use ``ConstantDerivative`` to simulate inflow/outflow of a chemical to/from simulation domain

2025-07-05 17:51 UTC, maciekswat commented on docs/diffusion_solver_settings.rst
> +All standard solvers (`Flexible <flexible_diffusion_solver.html>`_, `Fast <fast_diffusion_solver_2D.html>`_, and `ReactionDiffusion <reaction_diffusion_solver.html>`_) by default
let's add reference to DiffusionSolverFE and it woudl be great to list it first becuase this is our main solver now

2025-07-05 17:52 UTC, maciekswat commented on docs/images/movies/constant_derivative_diffusion.gif
This is fine

2025-07-05 17:54 UTC, maciekswat commented on docs/section_pde_solvers.rst
> +For most use cases, we recommend `Diffusion Solver FE <diffusion_solver.html>`_. For the highest level of customization, we recommend `Reaction Diffusion Solver with Finite Volume Method (FVM) <react
LEt's use this reference `Diffusion Solver FE <diffusion_solver.html>`_ in the earlies section that I mentioned

2025-07-05 17:56 UTC, maciekswat requested changes
This looks very good, just a few changes. Also, GitHub says there is a branch conflict, so I would merge from master into this branch, resolve conflicts, and push back the updated branch with the suggested changes.

2025-07-07 01:50 UTC, fyffep commented on docs/diffusion_solver_settings.rst
> +All standard solvers (`Flexible <flexible_diffusion_solver.html>`_, `Fast <fast_diffusion_solver_2D.html>`_, and `ReactionDiffusion <reaction_diffusion_solver.html>`_) by default
Added it in a few places

2025-07-07 01:50 UTC, fyffep commented on docs/section_pde_solvers.rst
> +For most use cases, we recommend `Diffusion Solver FE <diffusion_solver.html>`_. For the highest level of customization, we recommend `Reaction Diffusion Solver with Finite Volume Method (FVM) <react
No changes here, right?

2025-07-07 17:16 UTC, maciekswat approved these changes

2025-07-07 17:16 UTC, merged